import { Goblin_One , Inter } from "next/font/google";
import "../../styles/globals.css";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";
import Popup from "@components/Popup/Popup";

const goblinOne = Goblin_One({
  weight: "400",
  variable: "--font-goblin-one",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "400",
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${goblinOne.variable} ${inter.variable}`}>
        <Header/>
        <main>
          {children}
          <Popup/>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
